-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 17:58:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mBBusBase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mBBusBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mBBusBase` DEFAULT CHARACTER SET utf8 ;
USE `mBBusBase` ;

-- -----------------------------------------------------
-- Table `mBBusBase`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mBBusBase`.`Route` (
  `idRoute` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoute`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mBBusBase`.`Bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mBBusBase`.`Bus` (
  `idBus` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `Route_idRoute` INT NOT NULL,
  PRIMARY KEY (`idBus`),
  INDEX `fk_Bus_Route1_idx` (`Route_idRoute` ASC) VISIBLE,
  CONSTRAINT `fk_Bus_Route1`
    FOREIGN KEY (`Route_idRoute`)
    REFERENCES `mBBusBase`.`Route` (`idRoute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mBBusBase`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mBBusBase`.`User` (
  `idUser` INT NOT NULL,
  `Discriminator` INT NULL,
  `first_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(90) NULL,
  `role` VARCHAR(45) NULL,
  `Bus_idBus` INT NULL,
  `User_idUser` INT NULL,
  `User_Bus_idBus` INT NOT NULL,
  PRIMARY KEY (`idUser`, `Bus_idBus`),
  INDEX `fk_User_Bus1_idx` (`Bus_idBus` ASC) VISIBLE,
  INDEX `fk_User_User1_idx` (`User_idUser` ASC, `User_Bus_idBus` ASC) VISIBLE,
  CONSTRAINT `fk_User_Bus1`
    FOREIGN KEY (`Bus_idBus`)
    REFERENCES `mBBusBase`.`Bus` (`idBus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_User1`
    FOREIGN KEY (`User_idUser` , `User_Bus_idBus`)
    REFERENCES `mBBusBase`.`User` (`idUser` , `Bus_idBus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mBBusBase`.`Assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mBBusBase`.`Assignment` (
  `idAssignment` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `date` DATE NULL,
  `User_idUser` INT NOT NULL,
  `User_Bus_idBus` INT NULL,
  `Route_idRoute` INT NOT NULL,
  PRIMARY KEY (`idAssignment`),
  INDEX `fk_Assignment_User1_idx` (`User_idUser` ASC, `User_Bus_idBus` ASC) VISIBLE,
  INDEX `fk_Assignment_Route1_idx` (`Route_idRoute` ASC) VISIBLE,
  CONSTRAINT `fk_Assignment_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mBBusBase`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Assignment_Route1`
    FOREIGN KEY (`Route_idRoute`)
    REFERENCES `mBBusBase`.`Route` (`idRoute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
